fork = false
frame = "full"
idle = true
maximized = false
mouse-cursor-icon = "arrow"
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = [] # Will use the bundled Fira Code Nerd Font by default
hinting = "full"
edging = "antialias"
size = 11.0

[[font.italic]]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[box-drawing]
# "font-glyph", "native" or "selected-native"
mode = "native"


[box-drawing.sizes]
default = [2, 4]  # Thin and thick values respectively, for all sizes

